AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless demo - Lambda + API Gateway

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.lambda_handler
      Runtime: python3.9
      Timeout: 10
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get
